### ISSUE TITLE
Singleton Push

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [tractr/directus-sync#106]
```
[00:02:40.194] INFO (29613): ---- Push schema ----
[00:02:41.157] INFO (29613): [snapshot] No changes to apply
[00:02:41.165] INFO (29613): ---- Clean up collections ----
[00:02:41.309] INFO (29613): [settings] Deleted 0 dangling items
[00:02:42.014] INFO (29613): [folders] Deleted 0 dangling items
[00:02:42.075] INFO (29613): [translations] Deleted 0 dangling items
[00:02:42.914] INFO (29613): [flows] Deleted 0 dangling items
[00:02:43.479] INFO (29613): [operations] Deleted 0 dangling items
[00:02:43.763] INFO (29613): [roles] Deleted 0 dangling items
[00:02:44.074] INFO (29613): [policies] Deleted 0 dangling items
[00:02:46.820] INFO (29613): [permissions] Deleted 0 dangling items
[00:02:46.914] INFO (29613): [dashboards] Deleted 0 dangling items
[00:02:47.011] INFO (29613): [panels] Deleted 0 dangling items
[00:02:47.072] INFO (29613): [presets] Deleted 0 dangling items
[00:02:47.072] INFO (29613): ---- Push: iteration 1 ----
[00:02:47.283] ERROR (29613): Local id already exists
    err: {
      "type": "ConflictError",
      "message": "Local id already exists",
      "stack":
          ConflictError: Local id already exists
              at SettingsIdMapperClient.<anonymous> (/Users/nilsbaumgartner/Documents/GitHub/rocket-meals/backend/sync/node_modules/directus-sync/dist/lib/services/extension-client.js:48:55)
              at Generator.next (<anonymous>)
              at fulfilled (/Users/nilsbaumgartner/Documents/GitHub/rocket-meals/backend/sync/node_modules/directus-sync/dist/lib/services/extension-client.js:14:58)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      "status": 409,
      "statusCode": 409,
      "expose": true
    }
```

as we tried to push, an existing singleton made problems.
We had a workaround by deleting all directus-sync map ids, then push again.

**Comment by muhdnajmuddin** [comment]
Hi, I ran into the same issue, can you help me to point out where are the directus-sync map ids located yea?

**Comment by EdouardDem** [comment]
Hi. How did. get this error ? Is it after a migration ? On which collection ?

It seems that the sync Id has been updated between 2 sync.

You don't have to delete all sync ids, you can use the following command :
`npx directus-sync helpers untrack --collection policies --id xxxx-xxxx-xxx`

If you prefer you can browse the sync ids map from Directus.

First, you have to activate the model :

![image](https://github.com/user-attachments/assets/cde39edf-f65e-4bd8-b6ad-96c53b9e94d0)

Then you can select on or more sync id map that cause the issue.
In your case it seems to be the `policies` table :

![image](https://github.com/user-attachments/assets/e0bf8dbd-8cd5-45d4-a39d-5f5b79e29e82)

**Comment by sethjgore** [comment]
I had the same issue and I believe the bug comes from:

sync ids require the local ids to be unique however, 

```the _sync_default_admin_role``` and ```_sync_default_admin_policy``` both are set with the same local id. You can see the screenshot above, the same errors apply. 

I haven't read through the code to see what's happening, but I assume it's either an assignment error or they both come from the same location.

**Comment by sethjgore** [comment]
I have identified the issue — both ```id-mapper-client.ts``` in collection and services have methods that return the same ID due to the nature of how Directus sets up admin role and policy. They both are THE SAME ID as shown in screenshots between ```Settings > User Role``` and ```Settings > Policies```

<img width="754" alt="Screenshot 2024-11-01 at 11 49 45 AM" src="https://github.com/user-attachments/assets/08af001a-8563-43a2-9804-56a1477cd02b">
<img width="792" alt="Screenshot 2024-11-01 at 11 49 37 AM" src="https://github.com/user-attachments/assets/5ce83fa6-af29-4f33-b50f-87b5caa889b1">
  

So, the methods that return the policy id and the role id return the same ID, which causes the error when ensuring that local IDs are unique. I would think that you would need to update wherever it enforces that to allow same local IDs if it is from a different table. That's my best guess. Hope this helps!

**Comment by EdouardDem** [comment]
@sethjgore That's a good guess. Thank you!
I will fix it soon
